// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package hitchhiker

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// newGuide is a goModule method implementation.
func (self *goModuleImpl) newGuide(questionArg string) (goGuide, error) {
	return nil, errors.ErrUnsupported
}

// checkMethod is a goModule method implementation.
func (self *goModuleImpl) checkMethod(valueArg int) (bool, error) {
	return false, errors.ErrUnsupported
}

// defaultGuideGetter is a goModule property getter method implementation.
func (self *goModuleImpl) defaultGuideGetter() (goGuide, error) {
	return nil, errors.ErrUnsupported
}

// goGuideImpl is an empty implementation of goGuide.
type goGuideImpl struct{}

var _ goGuide = (*goGuideImpl)(nil)

// checkMethod is a goGuide method implementation.
func (self *goGuideImpl) checkMethod(valueArg int) (bool, error) {
	return false, errors.ErrUnsupported
}

// questionGetter is a goGuide property getter method implementation.
func (self *goGuideImpl) questionGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// questionSetter is a goGuide property setter method.
func (self *goGuideImpl) questionSetter(questionArg string) error {
	return errors.ErrUnsupported
}

// answerGetter is a goGuide property getter method implementation.
func (self *goGuideImpl) answerGetter() (int, error) {
	return 0, errors.ErrUnsupported
}
