// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package state

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// activeVUsGetter is a goModule property getter method implementation.
func (self *goModuleImpl) activeVUsGetter() (int64, error) {
	return 0, errors.ErrUnsupported
}

// iterationGetter is a goModule property getter method implementation.
func (self *goModuleImpl) iterationGetter() (int64, error) {
	return 0, errors.ErrUnsupported
}

// vuIDGetter is a goModule property getter method implementation.
func (self *goModuleImpl) vuIDGetter() (uint64, error) {
	return 0, errors.ErrUnsupported
}

// vuIDFromRuntimeGetter is a goModule property getter method implementation.
func (self *goModuleImpl) vuIDFromRuntimeGetter() (int64, error) {
	return 0, errors.ErrUnsupported
}
