// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package faker

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// newFaker is a goModule method implementation.
func (self *goModuleImpl) newFaker(seedArg int64) (goFaker, error) {
	return nil, errors.ErrUnsupported
}

// fakerGetter is a goModule property getter method implementation.
func (self *goModuleImpl) fakerGetter() (goFaker, error) {
	return nil, errors.ErrUnsupported
}

// goFakerImpl is an empty implementation of goFaker.
type goFakerImpl struct{}

var _ goFaker = (*goFakerImpl)(nil)

// personGetter is a goFaker property getter method implementation.
func (self *goFakerImpl) personGetter() (goPerson, error) {
	return nil, errors.ErrUnsupported
}

// goPersonImpl is an empty implementation of goPerson.
type goPersonImpl struct{}

var _ goPerson = (*goPersonImpl)(nil)

// firstNameMethod is a goPerson method implementation.
func (self *goPersonImpl) firstNameMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// lastNameMethod is a goPerson method implementation.
func (self *goPersonImpl) lastNameMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// prefixMethod is a goPerson method implementation.
func (self *goPersonImpl) prefixMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// suffixMethod is a goPerson method implementation.
func (self *goPersonImpl) suffixMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// sexTypeMethod is a goPerson method implementation.
func (self *goPersonImpl) sexTypeMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// jobTitleMethod is a goPerson method implementation.
func (self *goPersonImpl) jobTitleMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// jobLevelMethod is a goPerson method implementation.
func (self *goPersonImpl) jobLevelMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// jobDescriptorMethod is a goPerson method implementation.
func (self *goPersonImpl) jobDescriptorMethod() (string, error) {
	return "", errors.ErrUnsupported
}
