// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package toml

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// parseMethod is a goModule method implementation.
func (self *goModuleImpl) parseMethod(textArg string) (interface{}, error) {
	return nil, errors.ErrUnsupported
}

// stringifyMethod is a goModule method implementation.
func (self *goModuleImpl) stringifyMethod(valueArg interface{}) (string, error) {
	return "", errors.ErrUnsupported
}
