// Code generated by tygor; DO NOT EDIT.

package testdata

import (
	"errors"
	"fmt"
	"github.com/dop251/goja"
	"time"
)

// jsBuiltin is the go binding for the JavaScript Builtin type.
type jsBuiltin interface {
	// iGetter is the go getter binding for the JavaScript i property.
	iGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// iSetter is the go setter binding for the JavaScript i property.
	iSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i8Getter is the go getter binding for the JavaScript i8 property.
	i8Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i8Setter is the go setter binding for the JavaScript i8 property.
	i8Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i16Getter is the go getter binding for the JavaScript i16 property.
	i16Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i16Setter is the go setter binding for the JavaScript i16 property.
	i16Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i32Getter is the go getter binding for the JavaScript i32 property.
	i32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i32Setter is the go setter binding for the JavaScript i32 property.
	i32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i64Getter is the go getter binding for the JavaScript i64 property.
	i64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// i64Setter is the go setter binding for the JavaScript i64 property.
	i64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// uGetter is the go getter binding for the JavaScript u property.
	uGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// uSetter is the go setter binding for the JavaScript u property.
	uSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u8Getter is the go getter binding for the JavaScript u8 property.
	u8Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u8Setter is the go setter binding for the JavaScript u8 property.
	u8Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u16Getter is the go getter binding for the JavaScript u16 property.
	u16Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u16Setter is the go setter binding for the JavaScript u16 property.
	u16Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u32Getter is the go getter binding for the JavaScript u32 property.
	u32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u32Setter is the go setter binding for the JavaScript u32 property.
	u32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u64Getter is the go getter binding for the JavaScript u64 property.
	u64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// u64Setter is the go setter binding for the JavaScript u64 property.
	u64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// bGetter is the go getter binding for the JavaScript b property.
	bGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// bSetter is the go setter binding for the JavaScript b property.
	bSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// rGetter is the go getter binding for the JavaScript r property.
	rGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// rSetter is the go setter binding for the JavaScript r property.
	rSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// f32Getter is the go getter binding for the JavaScript f32 property.
	f32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// f32Setter is the go setter binding for the JavaScript f32 property.
	f32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// f64Getter is the go getter binding for the JavaScript f64 property.
	f64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// f64Setter is the go setter binding for the JavaScript f64 property.
	f64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// nGetter is the go getter binding for the JavaScript n property.
	nGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// nSetter is the go setter binding for the JavaScript n property.
	nSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// sGetter is the go getter binding for the JavaScript s property.
	sGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// sSetter is the go setter binding for the JavaScript s property.
	sSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// aGetter is the go getter binding for the JavaScript a property.
	aGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// aSetter is the go setter binding for the JavaScript a property.
	aSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// oGetter is the go getter binding for the JavaScript o property.
	oGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// oSetter is the go setter binding for the JavaScript o property.
	oSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// dGetter is the go getter binding for the JavaScript d property.
	dGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// dSetter is the go setter binding for the JavaScript d property.
	dSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// abGetter is the go getter binding for the JavaScript ab property.
	abGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// abSetter is the go setter binding for the JavaScript ab property.
	abSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value
}

// goBuiltin is the go representation of the JavaScript Builtin type.
type goBuiltin interface {
	// iGetter is the go getter method for the i property.
	iGetter() (int, error)

	// iSetter is the go setter method for the i property.
	iSetter(v int) error

	// i8Getter is the go getter method for the i8 property.
	i8Getter() (int8, error)

	// i8Setter is the go setter method for the i8 property.
	i8Setter(v int8) error

	// i16Getter is the go getter method for the i16 property.
	i16Getter() (int16, error)

	// i16Setter is the go setter method for the i16 property.
	i16Setter(v int16) error

	// i32Getter is the go getter method for the i32 property.
	i32Getter() (int32, error)

	// i32Setter is the go setter method for the i32 property.
	i32Setter(v int32) error

	// i64Getter is the go getter method for the i64 property.
	i64Getter() (int64, error)

	// i64Setter is the go setter method for the i64 property.
	i64Setter(v int64) error

	// uGetter is the go getter method for the u property.
	uGetter() (uint, error)

	// uSetter is the go setter method for the u property.
	uSetter(v uint) error

	// u8Getter is the go getter method for the u8 property.
	u8Getter() (uint8, error)

	// u8Setter is the go setter method for the u8 property.
	u8Setter(v uint8) error

	// u16Getter is the go getter method for the u16 property.
	u16Getter() (uint16, error)

	// u16Setter is the go setter method for the u16 property.
	u16Setter(v uint16) error

	// u32Getter is the go getter method for the u32 property.
	u32Getter() (uint32, error)

	// u32Setter is the go setter method for the u32 property.
	u32Setter(v uint32) error

	// u64Getter is the go getter method for the u64 property.
	u64Getter() (uint64, error)

	// u64Setter is the go setter method for the u64 property.
	u64Setter(v uint64) error

	// bGetter is the go getter method for the b property.
	bGetter() (byte, error)

	// bSetter is the go setter method for the b property.
	bSetter(v byte) error

	// rGetter is the go getter method for the r property.
	rGetter() (rune, error)

	// rSetter is the go setter method for the r property.
	rSetter(v rune) error

	// f32Getter is the go getter method for the f32 property.
	f32Getter() (float32, error)

	// f32Setter is the go setter method for the f32 property.
	f32Setter(v float32) error

	// f64Getter is the go getter method for the f64 property.
	f64Getter() (float64, error)

	// f64Setter is the go setter method for the f64 property.
	f64Setter(v float64) error

	// nGetter is the go getter method for the n property.
	nGetter() (float64, error)

	// nSetter is the go setter method for the n property.
	nSetter(v float64) error

	// sGetter is the go getter method for the s property.
	sGetter() (string, error)

	// sSetter is the go setter method for the s property.
	sSetter(v string) error

	// aGetter is the go getter method for the a property.
	aGetter() (interface{}, error)

	// aSetter is the go setter method for the a property.
	aSetter(v interface{}) error

	// oGetter is the go getter method for the o property.
	oGetter() (interface{}, error)

	// oSetter is the go setter method for the o property.
	oSetter(v interface{}) error

	// dGetter is the go getter method for the d property.
	dGetter() (time.Time, error)

	// dSetter is the go setter method for the d property.
	dSetter(v time.Time) error

	// abGetter is the go getter method for the ab property.
	abGetter() ([]byte, error)

	// abSetter is the go setter method for the ab property.
	abSetter(v []byte) error
}

// jsBuiltinAdapter converts goBuiltin to jsBuiltin.
type jsBuiltinAdapter struct {
	adaptee goBuiltin
}

var _ jsBuiltin = (*jsBuiltinAdapter)(nil)

// iGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) iGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.iGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// iSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) iSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.iSetter(int(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// i8Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) i8Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.i8Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// i8Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) i8Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.i8Setter(int8(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// i16Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) i16Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.i16Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// i16Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) i16Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.i16Setter(int16(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// i32Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) i32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.i32Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// i32Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) i32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.i32Setter(int32(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// i64Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) i64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.i64Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// i64Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) i64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.i64Setter(call.Argument(0).ToInteger())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// uGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) uGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.uGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// uSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) uSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.uSetter(uint(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// u8Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) u8Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.u8Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// u8Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) u8Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.u8Setter(uint8(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// u16Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) u16Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.u16Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// u16Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) u16Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.u16Setter(uint16(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// u32Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) u32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.u32Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// u32Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) u32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.u32Setter(uint32(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// u64Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) u64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.u64Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// u64Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) u64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.u64Setter(uint64(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// bGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) bGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.bGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// bSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) bSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.bSetter(byte(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// rGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) rGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.rGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// rSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) rSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.rSetter(rune(call.Argument(0).ToInteger()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// f32Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) f32Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.f32Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// f32Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) f32Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.f32Setter(float32(call.Argument(0).ToFloat()))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// f64Getter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) f64Getter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.f64Getter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// f64Setter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) f64Setter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.f64Setter(call.Argument(0).ToFloat())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// nGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) nGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.nGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// nSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) nSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.nSetter(call.Argument(0).ToFloat())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// sGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) sGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.sGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// sSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) sSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.sSetter(call.Argument(0).String())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// aGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) aGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.aGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// aSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) aSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.aSetter(call.Argument(0).Export())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// oGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) oGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.oGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// oSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) oSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.oSetter(call.Argument(0).Export())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// dGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) dGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.dGetter()
	if err != nil {
		panic(err)
	}

	return jsDateFromTime(v, vm)
}

// dSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) dSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.dSetter(goTimeFromDate(call.Argument(0), vm))
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// abGetter is a jsBuiltin property getter adapter method.
func (self *jsBuiltinAdapter) abGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.abGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(vm.NewArrayBuffer(v))
}

// abSetter is a jsBuiltin property setter adapter method.
func (self *jsBuiltinAdapter) abSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.abSetter((call.Argument(0).Export().(goja.ArrayBuffer)).Bytes())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// goBuiltinAdapter converts goja Object to goBuiltin.
type goBuiltinAdapter struct {
	adaptee *goja.Object
	vm      *goja.Runtime
}

var _ goBuiltin = (*goBuiltinAdapter)(nil)

// iGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) iGetter() (int, error) {
	return int(self.adaptee.Get("i").ToInteger()), nil
}

// iSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) iSetter(v int) error {
	return self.adaptee.Set("i", v)
}

// i8Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) i8Getter() (int8, error) {
	return int8(self.adaptee.Get("i8").ToInteger()), nil
}

// i8Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) i8Setter(v int8) error {
	return self.adaptee.Set("i8", v)
}

// i16Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) i16Getter() (int16, error) {
	return int16(self.adaptee.Get("i16").ToInteger()), nil
}

// i16Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) i16Setter(v int16) error {
	return self.adaptee.Set("i16", v)
}

// i32Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) i32Getter() (int32, error) {
	return int32(self.adaptee.Get("i32").ToInteger()), nil
}

// i32Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) i32Setter(v int32) error {
	return self.adaptee.Set("i32", v)
}

// i64Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) i64Getter() (int64, error) {
	return self.adaptee.Get("i64").ToInteger(), nil
}

// i64Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) i64Setter(v int64) error {
	return self.adaptee.Set("i64", v)
}

// uGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) uGetter() (uint, error) {
	return uint(self.adaptee.Get("u").ToInteger()), nil
}

// uSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) uSetter(v uint) error {
	return self.adaptee.Set("u", v)
}

// u8Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) u8Getter() (uint8, error) {
	return uint8(self.adaptee.Get("u8").ToInteger()), nil
}

// u8Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) u8Setter(v uint8) error {
	return self.adaptee.Set("u8", v)
}

// u16Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) u16Getter() (uint16, error) {
	return uint16(self.adaptee.Get("u16").ToInteger()), nil
}

// u16Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) u16Setter(v uint16) error {
	return self.adaptee.Set("u16", v)
}

// u32Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) u32Getter() (uint32, error) {
	return uint32(self.adaptee.Get("u32").ToInteger()), nil
}

// u32Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) u32Setter(v uint32) error {
	return self.adaptee.Set("u32", v)
}

// u64Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) u64Getter() (uint64, error) {
	return uint64(self.adaptee.Get("u64").ToInteger()), nil
}

// u64Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) u64Setter(v uint64) error {
	return self.adaptee.Set("u64", v)
}

// bGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) bGetter() (byte, error) {
	return byte(self.adaptee.Get("b").ToInteger()), nil
}

// bSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) bSetter(v byte) error {
	return self.adaptee.Set("b", v)
}

// rGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) rGetter() (rune, error) {
	return rune(self.adaptee.Get("r").ToInteger()), nil
}

// rSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) rSetter(v rune) error {
	return self.adaptee.Set("r", v)
}

// f32Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) f32Getter() (float32, error) {
	return float32(self.adaptee.Get("f32").ToFloat()), nil
}

// f32Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) f32Setter(v float32) error {
	return self.adaptee.Set("f32", v)
}

// f64Getter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) f64Getter() (float64, error) {
	return self.adaptee.Get("f64").ToFloat(), nil
}

// f64Setter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) f64Setter(v float64) error {
	return self.adaptee.Set("f64", v)
}

// nGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) nGetter() (float64, error) {
	return self.adaptee.Get("n").ToFloat(), nil
}

// nSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) nSetter(v float64) error {
	return self.adaptee.Set("n", v)
}

// sGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) sGetter() (string, error) {
	return self.adaptee.Get("s").String(), nil
}

// sSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) sSetter(v string) error {
	return self.adaptee.Set("s", v)
}

// aGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) aGetter() (interface{}, error) {
	return self.adaptee.Get("a").Export(), nil
}

// aSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) aSetter(v interface{}) error {
	return self.adaptee.Set("a", v)
}

// oGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) oGetter() (interface{}, error) {
	return self.adaptee.Get("o").Export(), nil
}

// oSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) oSetter(v interface{}) error {
	return self.adaptee.Set("o", v)
}

// dGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) dGetter() (time.Time, error) {
	return goTimeFromDate(self.adaptee.Get("d"), self.vm), nil
}

// dSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) dSetter(v time.Time) error {
	return self.adaptee.Set("d", v)
}

// abGetter is a goBuiltin property getter adapter method.
func (self *goBuiltinAdapter) abGetter() ([]byte, error) {
	return (self.adaptee.Get("ab").Export().(goja.ArrayBuffer)).Bytes(), nil
}

// abSetter is a goBuiltin property setter adapter method.
func (self *goBuiltinAdapter) abSetter(v []byte) error {
	return self.adaptee.Set("ab", v)
}

// jsBuiltinTo setup Builtin JavaScript object from jsBuiltin.
func jsBuiltinTo(src jsBuiltin, obj *goja.Object, vm *goja.Runtime) error {
	if err := obj.DefineAccessorProperty("i", vm.ToValue(src.iGetter), vm.ToValue(src.iSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("i8", vm.ToValue(src.i8Getter), vm.ToValue(src.i8Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("i16", vm.ToValue(src.i16Getter), vm.ToValue(src.i16Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("i32", vm.ToValue(src.i32Getter), vm.ToValue(src.i32Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("i64", vm.ToValue(src.i64Getter), vm.ToValue(src.i64Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("u", vm.ToValue(src.uGetter), vm.ToValue(src.uSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("u8", vm.ToValue(src.u8Getter), vm.ToValue(src.u8Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("u16", vm.ToValue(src.u16Getter), vm.ToValue(src.u16Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("u32", vm.ToValue(src.u32Getter), vm.ToValue(src.u32Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("u64", vm.ToValue(src.u64Getter), vm.ToValue(src.u64Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("b", vm.ToValue(src.bGetter), vm.ToValue(src.bSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("r", vm.ToValue(src.rGetter), vm.ToValue(src.rSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("f32", vm.ToValue(src.f32Getter), vm.ToValue(src.f32Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("f64", vm.ToValue(src.f64Getter), vm.ToValue(src.f64Setter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("n", vm.ToValue(src.nGetter), vm.ToValue(src.nSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("s", vm.ToValue(src.sGetter), vm.ToValue(src.sSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("a", vm.ToValue(src.aGetter), vm.ToValue(src.aSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("o", vm.ToValue(src.oGetter), vm.ToValue(src.oSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("d", vm.ToValue(src.dGetter), vm.ToValue(src.dSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	return obj.DefineAccessorProperty("ab", vm.ToValue(src.abGetter), vm.ToValue(src.abSetter), goja.FLAG_FALSE, goja.FLAG_TRUE)
}

// jsBuiltinFrom returns a jsBuiltin based on a goBuiltin.
func jsBuiltinFrom(adaptee goBuiltin) jsBuiltin {
	return &jsBuiltinAdapter{adaptee: adaptee}
}

// goBuiltinFrom returns a goBuiltin from goja Object.
func goBuiltinFrom(adaptee *goja.Object, vm *goja.Runtime) goBuiltin {
	return &goBuiltinAdapter{adaptee: adaptee, vm: vm}
}

// goBuiltinToObject returns a goja Object from goBuiltin.
func goBuiltinToObject(v goBuiltin, vm *goja.Runtime) *goja.Object {
	obj := vm.NewObject()

	err := jsBuiltinTo(jsBuiltinFrom(v), obj, vm)
	if err != nil {
		panic(err)
	}

	return obj
}
func goTimeFromDate(v goja.Value, vm *goja.Runtime) time.Time {
	getTime, ok := goja.AssertFunction(v.ToObject(vm).Get("getTime"))
	if !ok {
		panic(fmt.Errorf("%w: getTime", errors.ErrUnsupported))
	}

	ret, err := getTime(v)
	if err != nil {
		panic(err)
	}

	return time.UnixMilli(ret.ToInteger())
}

func jsDateFromTime(t time.Time, vm *goja.Runtime) goja.Value {
	d, err := vm.New(vm.Get("Date"), vm.ToValue(t.UnixMilli()))
	if err != nil {
		panic(err)
	}

	return d
}
