// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package testdata

import (
	"errors"
	"time"
)

// goBuiltinImpl is an empty implementation of goBuiltin.
type goBuiltinImpl struct{}

var _ goBuiltin = (*goBuiltinImpl)(nil)

// iGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) iGetter() (int, error) {
	return 0, errors.ErrUnsupported
}

// iSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) iSetter(iArg int) error {
	return errors.ErrUnsupported
}

// i8Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) i8Getter() (int8, error) {
	return 0, errors.ErrUnsupported
}

// i8Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) i8Setter(i8Arg int8) error {
	return errors.ErrUnsupported
}

// i16Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) i16Getter() (int16, error) {
	return 0, errors.ErrUnsupported
}

// i16Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) i16Setter(i16Arg int16) error {
	return errors.ErrUnsupported
}

// i32Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) i32Getter() (int32, error) {
	return 0, errors.ErrUnsupported
}

// i32Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) i32Setter(i32Arg int32) error {
	return errors.ErrUnsupported
}

// i64Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) i64Getter() (int64, error) {
	return 0, errors.ErrUnsupported
}

// i64Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) i64Setter(i64Arg int64) error {
	return errors.ErrUnsupported
}

// uGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) uGetter() (uint, error) {
	return 0, errors.ErrUnsupported
}

// uSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) uSetter(uArg uint) error {
	return errors.ErrUnsupported
}

// u8Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) u8Getter() (uint8, error) {
	return 0, errors.ErrUnsupported
}

// u8Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) u8Setter(u8Arg uint8) error {
	return errors.ErrUnsupported
}

// u16Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) u16Getter() (uint16, error) {
	return 0, errors.ErrUnsupported
}

// u16Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) u16Setter(u16Arg uint16) error {
	return errors.ErrUnsupported
}

// u32Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) u32Getter() (uint32, error) {
	return 0, errors.ErrUnsupported
}

// u32Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) u32Setter(u32Arg uint32) error {
	return errors.ErrUnsupported
}

// u64Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) u64Getter() (uint64, error) {
	return 0, errors.ErrUnsupported
}

// u64Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) u64Setter(u64Arg uint64) error {
	return errors.ErrUnsupported
}

// bGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) bGetter() (byte, error) {
	return 0, errors.ErrUnsupported
}

// bSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) bSetter(bArg byte) error {
	return errors.ErrUnsupported
}

// rGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) rGetter() (rune, error) {
	return 0, errors.ErrUnsupported
}

// rSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) rSetter(rArg rune) error {
	return errors.ErrUnsupported
}

// f32Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) f32Getter() (float32, error) {
	return 0, errors.ErrUnsupported
}

// f32Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) f32Setter(f32Arg float32) error {
	return errors.ErrUnsupported
}

// f64Getter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) f64Getter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// f64Setter is a goBuiltin property setter method.
func (self *goBuiltinImpl) f64Setter(f64Arg float64) error {
	return errors.ErrUnsupported
}

// nGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) nGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// nSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) nSetter(nArg float64) error {
	return errors.ErrUnsupported
}

// sGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) sGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// sSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) sSetter(sArg string) error {
	return errors.ErrUnsupported
}

// aGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) aGetter() (interface{}, error) {
	return nil, errors.ErrUnsupported
}

// aSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) aSetter(aArg interface{}) error {
	return errors.ErrUnsupported
}

// oGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) oGetter() (interface{}, error) {
	return nil, errors.ErrUnsupported
}

// oSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) oSetter(oArg interface{}) error {
	return errors.ErrUnsupported
}

// dGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) dGetter() (time.Time, error) {
	return time.Time{}, errors.ErrUnsupported
}

// dSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) dSetter(dArg time.Time) error {
	return errors.ErrUnsupported
}

// abGetter is a goBuiltin property getter method implementation.
func (self *goBuiltinImpl) abGetter() ([]byte, error) {
	return nil, errors.ErrUnsupported
}

// abSetter is a goBuiltin property setter method.
func (self *goBuiltinImpl) abSetter(abArg []byte) error {
	return errors.ErrUnsupported
}
