// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package testdata

import "errors"

// goLoremImpl is an empty implementation of goLorem.
type goLoremImpl struct{}

var _ goLorem = (*goLoremImpl)(nil)

// incididuntMethod is a goLorem method implementation.
func (self *goLoremImpl) incididuntMethod() (float64, error) {
	return 0, errors.ErrUnsupported
}

// excepteurMethod is a goLorem method implementation.
func (self *goLoremImpl) excepteurMethod(estArg float64, adArg string) (string, error) {
	return "", errors.ErrUnsupported
}

// cupidatatGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) cupidatatGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) laborisGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisSetter is a goLorem property setter method.
func (self *goLoremImpl) laborisSetter(laborisArg string) error {
	return errors.ErrUnsupported
}

// velitGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) velitGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// velitSetter is a goLorem property setter method.
func (self *goLoremImpl) velitSetter(velitArg float64) error {
	return errors.ErrUnsupported
}
