// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package testdata

import "errors"

// goIpsumImpl is an empty implementation of goIpsum.
type goIpsumImpl struct{}

var _ goIpsum = (*goIpsumImpl)(nil)

// incididuntMethod is a goIpsum method implementation.
func (self *goIpsumImpl) incididuntMethod() (float64, error) {
	return 0, errors.ErrUnsupported
}

// excepteurMethod is a goIpsum method implementation.
func (self *goIpsumImpl) excepteurMethod(estArg float64, adArg string) (string, error) {
	return "", errors.ErrUnsupported
}

// nostrudMethod is a goIpsum method implementation.
func (self *goIpsumImpl) nostrudMethod(duisArg bool) error {
	return errors.ErrUnsupported
}

// cupidatatGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) cupidatatGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) laborisGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisSetter is a goIpsum property setter method.
func (self *goIpsumImpl) laborisSetter(laborisArg string) error {
	return errors.ErrUnsupported
}

// velitGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) velitGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// velitSetter is a goIpsum property setter method.
func (self *goIpsumImpl) velitSetter(velitArg float64) error {
	return errors.ErrUnsupported
}
