// Code generated by tygor; DO NOT EDIT.

package testdata

import (
	"errors"
	"fmt"
	"github.com/dop251/goja"
	"time"
)

// jsIpsum is the go binding for the JavaScript Ipsum type.
//
// TSDoc:
// Exercitation non duis qui ad.
//
// Ipsum dolore nostrud deserunt proident non.
type jsIpsum interface {
	// incididuntMethod is the go binding for the JavaScript incididunt method.
	//
	// TSDoc:
	// Duis duis proident fugiat sunt non duis non mollit nulla tempor et.
	//
	// Culpa et quis incididunt tempor amet.
	incididuntMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// excepteurMethod is the go binding for the JavaScript excepteur method.
	//
	// TSDoc:
	// Amet pariatur dolor minim velit ea deserunt dolor.
	//
	// Ex tempor culpa sit Lorem quis.
	excepteurMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// nostrudMethod is the go binding for the JavaScript nostrud method.
	//
	// TSDoc:
	// Ad esse et dolor proident.
	nostrudMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// cupidatatGetter is the go getter binding for the JavaScript cupidatat property.
	//
	// TSDoc:
	// Id eiusmod tempor sunt est.
	cupidatatGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// laborisGetter is the go getter binding for the JavaScript laboris property.
	//
	// TSDoc:
	// Nisi est veniam eiusmod exercitation quis.
	laborisGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// laborisSetter is the go setter binding for the JavaScript laboris property.
	//
	// TSDoc:
	// Nisi est veniam eiusmod exercitation quis.
	laborisSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// velitGetter is the go getter binding for the JavaScript velit property.
	//
	// TSDoc:
	// Excepteur tempor adipisicing occaecat incididunt.
	velitGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value

	// velitSetter is the go setter binding for the JavaScript velit property.
	//
	// TSDoc:
	// Excepteur tempor adipisicing occaecat incididunt.
	velitSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value
}

// goIpsum is the go representation of the JavaScript Ipsum type.
//
// TSDoc:
// Exercitation non duis qui ad.
//
// Ipsum dolore nostrud deserunt proident non.
type goIpsum interface {
	// incididuntMethod is the go representation of the incididunt method.
	//
	// TSDoc:
	// Duis duis proident fugiat sunt non duis non mollit nulla tempor et.
	//
	// Culpa et quis incididunt tempor amet.
	incididuntMethod() (float64, error)

	// excepteurMethod is the go representation of the excepteur method.
	//
	// TSDoc:
	// Amet pariatur dolor minim velit ea deserunt dolor.
	//
	// Ex tempor culpa sit Lorem quis.
	excepteurMethod(estArg float64, adArg string) (string, error)

	// nostrudMethod is the go representation of the nostrud method.
	//
	// TSDoc:
	// Ad esse et dolor proident.
	nostrudMethod(duisArg bool) error

	// cupidatatGetter is the go getter method for the cupidatat property.
	//
	// TSDoc:
	// Id eiusmod tempor sunt est.
	cupidatatGetter() (string, error)

	// laborisGetter is the go getter method for the laboris property.
	//
	// TSDoc:
	// Nisi est veniam eiusmod exercitation quis.
	laborisGetter() (string, error)

	// laborisSetter is the go setter method for the laboris property.
	//
	// TSDoc:
	// Nisi est veniam eiusmod exercitation quis.
	laborisSetter(v string) error

	// velitGetter is the go getter method for the velit property.
	//
	// TSDoc:
	// Excepteur tempor adipisicing occaecat incididunt.
	velitGetter() (float64, error)

	// velitSetter is the go setter method for the velit property.
	//
	// TSDoc:
	// Excepteur tempor adipisicing occaecat incididunt.
	velitSetter(v float64) error
}

// jsIpsumAdapter converts goIpsum to jsIpsum.
type jsIpsumAdapter struct {
	adaptee goIpsum
}

var _ jsIpsum = (*jsIpsumAdapter)(nil)

// incididuntMethod is a jsIpsum adapter method.
func (self *jsIpsumAdapter) incididuntMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.incididuntMethod()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// excepteurMethod is a jsIpsum adapter method.
func (self *jsIpsumAdapter) excepteurMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.excepteurMethod(call.Argument(0).ToFloat(), call.Argument(1).String())
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// nostrudMethod is a jsIpsum adapter method.
func (self *jsIpsumAdapter) nostrudMethod(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.nostrudMethod(call.Argument(0).ToBoolean())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// cupidatatGetter is a jsIpsum property getter adapter method.
func (self *jsIpsumAdapter) cupidatatGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.cupidatatGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// laborisGetter is a jsIpsum property getter adapter method.
func (self *jsIpsumAdapter) laborisGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.laborisGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// laborisSetter is a jsIpsum property setter adapter method.
func (self *jsIpsumAdapter) laborisSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.laborisSetter(call.Argument(0).String())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// velitGetter is a jsIpsum property getter adapter method.
func (self *jsIpsumAdapter) velitGetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	v, err := self.adaptee.velitGetter()
	if err != nil {
		panic(err)
	}

	return vm.ToValue(v)
}

// velitSetter is a jsIpsum property setter adapter method.
func (self *jsIpsumAdapter) velitSetter(call goja.FunctionCall, vm *goja.Runtime) goja.Value {
	err := self.adaptee.velitSetter(call.Argument(0).ToFloat())
	if err != nil {
		panic(err)
	}

	return goja.Undefined()
}

// goIpsumAdapter converts goja Object to goIpsum.
type goIpsumAdapter struct {
	adaptee *goja.Object
	vm      *goja.Runtime
}

var _ goIpsum = (*goIpsumAdapter)(nil)

// incididuntMethod is a incididunt adapter method.
func (self *goIpsumAdapter) incididuntMethod() (float64, error) {
	fun, ok := goja.AssertFunction(self.adaptee.Get("incididunt"))
	if !ok {
		return 0, fmt.Errorf("%w: incididunt", errors.ErrUnsupported)
	}

	res, err := fun(self.adaptee)
	if err != nil {
		return 0, err
	}

	return res.ToFloat(), nil
}

// excepteurMethod is a excepteur adapter method.
func (self *goIpsumAdapter) excepteurMethod(estArg float64, adArg string) (string, error) {
	fun, ok := goja.AssertFunction(self.adaptee.Get("excepteur"))
	if !ok {
		return "", fmt.Errorf("%w: excepteur", errors.ErrUnsupported)
	}

	res, err := fun(self.adaptee)
	if err != nil {
		return "", err
	}

	return res.String(), nil
}

// nostrudMethod is a nostrud adapter method.
func (self *goIpsumAdapter) nostrudMethod(duisArg bool) error {
	fun, ok := goja.AssertFunction(self.adaptee.Get("nostrud"))
	if !ok {
		return fmt.Errorf("%w: nostrud", errors.ErrUnsupported)
	}

	_, err := fun(self.adaptee)

	return err
}

// cupidatatGetter is a goIpsum property getter adapter method.
func (self *goIpsumAdapter) cupidatatGetter() (string, error) {
	return self.adaptee.Get("cupidatat").String(), nil
}

// laborisGetter is a goIpsum property getter adapter method.
func (self *goIpsumAdapter) laborisGetter() (string, error) {
	return self.adaptee.Get("laboris").String(), nil
}

// laborisSetter is a goIpsum property setter adapter method.
func (self *goIpsumAdapter) laborisSetter(v string) error {
	return self.adaptee.Set("laboris", v)
}

// velitGetter is a goIpsum property getter adapter method.
func (self *goIpsumAdapter) velitGetter() (float64, error) {
	return self.adaptee.Get("velit").ToFloat(), nil
}

// velitSetter is a goIpsum property setter adapter method.
func (self *goIpsumAdapter) velitSetter(v float64) error {
	return self.adaptee.Set("velit", v)
}

// jsIpsumTo setup Ipsum JavaScript object from jsIpsum.
func jsIpsumTo(src jsIpsum, obj *goja.Object, vm *goja.Runtime) error {
	if err := obj.Set("incididunt", src.incididuntMethod); err != nil {
		return err
	}

	if err := obj.Set("excepteur", src.excepteurMethod); err != nil {
		return err
	}

	if err := obj.Set("nostrud", src.nostrudMethod); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("cupidatat", vm.ToValue(src.cupidatatGetter), goja.Undefined(), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	if err := obj.DefineAccessorProperty("laboris", vm.ToValue(src.laborisGetter), vm.ToValue(src.laborisSetter), goja.FLAG_FALSE, goja.FLAG_TRUE); err != nil {
		return err
	}

	return obj.DefineAccessorProperty("velit", vm.ToValue(src.velitGetter), vm.ToValue(src.velitSetter), goja.FLAG_FALSE, goja.FLAG_TRUE)
}

// jsIpsumFrom returns a jsIpsum based on a goIpsum.
func jsIpsumFrom(adaptee goIpsum) jsIpsum {
	return &jsIpsumAdapter{adaptee: adaptee}
}

// goIpsumFrom returns a goIpsum from goja Object.
func goIpsumFrom(adaptee *goja.Object, vm *goja.Runtime) goIpsum {
	return &goIpsumAdapter{adaptee: adaptee, vm: vm}
}

// goIpsumToObject returns a goja Object from goIpsum.
func goIpsumToObject(v goIpsum, vm *goja.Runtime) *goja.Object {
	obj := vm.NewObject()

	err := jsIpsumTo(jsIpsumFrom(v), obj, vm)
	if err != nil {
		panic(err)
	}

	return obj
}
func goTimeFromDate(v goja.Value, vm *goja.Runtime) time.Time {
	getTime, ok := goja.AssertFunction(v.ToObject(vm).Get("getTime"))
	if !ok {
		panic(fmt.Errorf("%w: getTime", errors.ErrUnsupported))
	}

	ret, err := getTime(v)
	if err != nil {
		panic(err)
	}

	return time.UnixMilli(ret.ToInteger())
}

func jsDateFromTime(t time.Time, vm *goja.Runtime) goja.Value {
	d, err := vm.New(vm.Get("Date"), vm.ToValue(t.UnixMilli()))
	if err != nil {
		panic(err)
	}

	return d
}
