// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package testdata

import (
	"errors"
	"go.k6.io/k6/js/modules"
	"time"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// loremMethod is a goModule method implementation.
func (self *goModuleImpl) loremMethod() (string, error) {
	return "", errors.ErrUnsupported
}

// irureMethod is a goModule method implementation.
func (self *goModuleImpl) irureMethod(enimArg bool, quisArg string, consequatArg float64) error {
	return errors.ErrUnsupported
}

// newLorem is a goModule method implementation.
func (self *goModuleImpl) newLorem(nonArg string, occaecatArg bool, animArg float64) (goLorem, error) {
	return nil, errors.ErrUnsupported
}

// laborumGetter is a goModule property getter method implementation.
func (self *goModuleImpl) laborumGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// doloreGetter is a goModule property getter method implementation.
func (self *goModuleImpl) doloreGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// ametGetter is a goModule property getter method implementation.
func (self *goModuleImpl) ametGetter() (time.Time, error) {
	return time.Time{}, errors.ErrUnsupported
}

// goLoremImpl is an empty implementation of goLorem.
type goLoremImpl struct{}

var _ goLorem = (*goLoremImpl)(nil)

// incididuntMethod is a goLorem method implementation.
func (self *goLoremImpl) incididuntMethod() (float64, error) {
	return 0, errors.ErrUnsupported
}

// excepteurMethod is a goLorem method implementation.
func (self *goLoremImpl) excepteurMethod(estArg float64, adArg string) (string, error) {
	return "", errors.ErrUnsupported
}

// cupidatatGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) cupidatatGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) laborisGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisSetter is a goLorem property setter method.
func (self *goLoremImpl) laborisSetter(laborisArg string) error {
	return errors.ErrUnsupported
}

// velitGetter is a goLorem property getter method implementation.
func (self *goLoremImpl) velitGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// velitSetter is a goLorem property setter method.
func (self *goLoremImpl) velitSetter(velitArg float64) error {
	return errors.ErrUnsupported
}

// goIpsumImpl is an empty implementation of goIpsum.
type goIpsumImpl struct{}

var _ goIpsum = (*goIpsumImpl)(nil)

// incididuntMethod is a goIpsum method implementation.
func (self *goIpsumImpl) incididuntMethod() (float64, error) {
	return 0, errors.ErrUnsupported
}

// excepteurMethod is a goIpsum method implementation.
func (self *goIpsumImpl) excepteurMethod(estArg float64, adArg string) (string, error) {
	return "", errors.ErrUnsupported
}

// nostrudMethod is a goIpsum method implementation.
func (self *goIpsumImpl) nostrudMethod(duisArg bool) error {
	return errors.ErrUnsupported
}

// cupidatatGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) cupidatatGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) laborisGetter() (string, error) {
	return "", errors.ErrUnsupported
}

// laborisSetter is a goIpsum property setter method.
func (self *goIpsumImpl) laborisSetter(laborisArg string) error {
	return errors.ErrUnsupported
}

// velitGetter is a goIpsum property getter method implementation.
func (self *goIpsumImpl) velitGetter() (float64, error) {
	return 0, errors.ErrUnsupported
}

// velitSetter is a goIpsum property setter method.
func (self *goIpsumImpl) velitSetter(velitArg float64) error {
	return errors.ErrUnsupported
}
