name: marp
concurrency: marp

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - intro
    paths:
      - "docs/**"
      - "examples/faker/index.html"
      - ".github/workflows/marp.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ensure docs dir exists
        run: mkdir -p build/docs

      # BEGIN: intro
      - name: Ensure intro dir exists
        run: mkdir -p build/docs/intro
      - name: Marp Build (HTML)
        uses: docker://marpteam/marp-cli:v3.2.0
        with:
          args: docs/intro/README.md -o build/docs/intro/index.html
        env:
          MARP_USER: root:root
      - name: Ensure intro/faker dir exists
        run: mkdir -p build/docs/intro/faker
      - name: Copy faker HTML docs to intro/faker dir
        run: cp examples/faker/index.html build/docs/intro/faker/
      # END: intro

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build/docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
